upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name 20.203.106.247 dscc-cw1-taskmanager-00016014.uaenorth.cloudapp.azure.com;
    return 301 https://dscc-cw1-taskmanager-00016014.uaenorth.cloudapp.azure.com$request_uri;
}

server {
    listen 443 ssl;
    server_name dscc-cw1-taskmanager-00016014.uaenorth.cloudapp.azure.com;

    ssl_certificate /certs/fullchain1.pem;
    ssl_certificate_key /certs/privkey1.pem;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
